from __future__ import annotations

from pathlib import Path
from typing import Protocol

from ..research.models import ResearchArtifact
from ..schemas.splits import SplitDefinition
from ..schemas.strategy_spec import StrategySpec
from .models import AdapterCapabilities, AdapterHealth, AdapterIdentity, BacktestRun, DataAvailability, PhaseDEvent, PhaseEEligibility


class StrategyAdapter(Protocol):
    identity: AdapterIdentity
    capabilities: AdapterCapabilities

    def health(self, specification: StrategySpec) -> AdapterHealth: ...
    def data_availability(self, specification: StrategySpec) -> list[DataAvailability]: ...
    def run_baseline(self, spec: StrategySpec, split: SplitDefinition, output_dir: Path) -> ResearchArtifact: ...
    def run_parameter_experiment(self, spec: StrategySpec, split: SplitDefinition, parameters: dict, output_dir: Path, experiment_id: str) -> ResearchArtifact: ...
    def run_walk_forward(self, spec: StrategySpec, split: SplitDefinition, parameters: dict, output_dir: Path) -> ResearchArtifact: ...
    def run_holdout(self, spec: StrategySpec, split: SplitDefinition, parameters: dict, output_dir: Path) -> ResearchArtifact: ...
    def run_stress_test(self, spec: StrategySpec, split: SplitDefinition, parameters: dict, output_dir: Path) -> ResearchArtifact: ...
    def run_throughput_analysis(self, spec: StrategySpec, split: SplitDefinition, parameters: dict, output_dir: Path) -> ResearchArtifact: ...
    def normalized_last_run(self) -> BacktestRun | None: ...
    def phase_d_export(self, spec: StrategySpec, candidate_hash: str) -> list[PhaseDEvent]: ...
    def phase_e_export(self, spec: StrategySpec, candidate_hash: str, phase_c_classification: str, phase_d_classification: str | None) -> PhaseEEligibility: ...
