from __future__ import annotations

import hashlib
import json
import os
import shutil
import site
import subprocess
import sys
from pathlib import Path
from typing import Any

from ..phase_b.redaction import redact_secrets


class IsolationError(RuntimeError):
    """Raised when an external job cannot be proven to be isolated."""


# These are repository-local, ignored fixture trees used by the deterministic
# research test suites.  They are copied verbatim; they are never generated by
# the executor and are not research outputs.
REQUIRED_FIXTURE_PATHS = (
    Path("research_registry/spec_drafts"),
    Path("tests/fixtures"),
)


def _creationflags() -> int:
    return getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0


def _resolved(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def _inside(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def build_isolated_environment(
    worktree_root: str | Path,
    *,
    repository_root: str | Path | None = None,
    base_environment: dict[str, str] | None = None,
) -> tuple[dict[str, str], dict[str, Any]]:
    """Build the only environment allowed for Codex and verification.

    The primary checkout's source paths are removed from PYTHONPATH and the
    worktree source directory is inserted first.  User-site imports are
    disabled so a stale editable install cannot take precedence.
    """

    worktree = _resolved(worktree_root)
    primary = _resolved(repository_root or worktree)
    primary_src = (primary / "src").resolve()
    worktree_src = (worktree / "src").resolve()
    source_entries = (base_environment or os.environ).get("PYTHONPATH", "").split(os.pathsep)
    retained: list[str] = []
    removed: list[str] = []
    for raw in source_entries:
        if not raw:
            continue
        candidate = _resolved(raw)
        if candidate == primary_src or candidate == primary or _inside(candidate, primary_src):
            removed.append(str(candidate))
        else:
            retained.append(str(candidate))
    # Keep third-party tooling available while still disabling implicit user
    # site injection.  Explicitly listing the user-site directory is safe here
    # because only the primary checkout source paths are forbidden.
    user_site_required = False
    try:
        user_site = _resolved(site.getusersitepackages())
        if user_site.is_dir():
            user_site_required = any((user_site / module).exists() for module in ("pytest", "yaml", "pydantic", "pyarrow"))
            if user_site != primary_src and user_site not in {_resolved(item) for item in retained}:
                retained.append(str(user_site))
    except (OSError, AttributeError):
        pass
    entries = [str(worktree_src), *retained]
    environment = dict(base_environment or os.environ)
    environment["PYTHONPATH"] = os.pathsep.join(entries)
    if not user_site_required:
        environment["PYTHONNOUSERSITE"] = "1"
    else:
        # The installed verification toolchain lives in the user site on this
        # machine.  Suppressing it would make child test processes that set a
        # minimal PYTHONPATH unable to import pytest/PyYAML.  The user site is
        # still explicit in PYTHONPATH and the primary source path remains
        # removed.
        environment.pop("PYTHONNOUSERSITE", None)
    report = {
        "worktree_root": str(worktree),
        "repository_root": str(primary),
        "python_executable": str(Path(sys.executable).resolve()),
        "pythonpath": entries,
        "removed_pythonpath": removed,
        "pythonno_usersite": not user_site_required,
        "user_site_explicit": user_site_required,
    }
    return environment, report


def normalize_python_command(command: list[str]) -> list[str]:
    """Use the current interpreter for Python commands in external jobs."""

    if not command:
        raise ValueError("external command may not be empty")
    first = Path(command[0]).name.casefold()
    if first in {"python", "python.exe", "python3", "python3.exe", "py", "py.exe"}:
        return [sys.executable, *command[1:]]
    return list(command)


def pytest_command(command: list[str], basetemp: str | Path) -> list[str]:
    """Add deterministic, writable pytest settings without changing tests."""

    normalized = normalize_python_command(command)
    is_pytest = "pytest" in {item.casefold() for item in normalized} or (
        "-m" in normalized and normalized[normalized.index("-m") + 1 : normalized.index("-m") + 2] == ["pytest"]
    )
    if not is_pytest:
        return normalized
    result = list(normalized)
    if "no:cacheprovider" not in result:
        result.extend(["-p", "no:cacheprovider"])
    if not any(item == "--basetemp" or item.startswith("--basetemp=") for item in result):
        result.extend(["--basetemp", str(_resolved(basetemp))])
    return result


def import_origin_preflight(
    worktree_root: str | Path,
    *,
    environment: dict[str, str],
    runner=subprocess.run,
) -> dict[str, Any]:
    """Verify that ``research_pipeline`` resolves from the worktree only."""

    worktree = _resolved(worktree_root)
    expected = (worktree / "src").resolve()
    command = [sys.executable, "-c", "import research_pipeline; print(research_pipeline.__file__ or '')"]
    try:
        result = runner(
            command,
            cwd=str(worktree),
            env=environment,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=False,
            creationflags=_creationflags(),
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise IsolationError(f"import-origin preflight could not execute: {redact_secrets(str(exc))}") from exc
    output = redact_secrets((result.stdout or "").strip())
    origin = Path(output.splitlines()[-1]).resolve() if output else None
    valid = result.returncode == 0 and origin is not None and _inside(origin, expected)
    report = {
        "command": command,
        "cwd": str(worktree),
        "origin": str(origin) if origin else None,
        "expected_source_root": str(expected),
        "valid": valid,
        "exit_code": result.returncode,
        "stdout": output[-2000:],
        "stderr": redact_secrets((result.stderr or "")[-2000:]),
    }
    if not valid:
        raise IsolationError(
            "import-origin mismatch: research_pipeline did not resolve inside the isolated worktree "
            f"(origin={report['origin']!r}, expected={expected})"
        )
    return report


def prepare_required_fixtures(
    repository_root: str | Path,
    worktree_root: str | Path,
    *,
    required_paths: tuple[Path, ...] = REQUIRED_FIXTURE_PATHS,
) -> dict[str, Any]:
    """Copy required ignored fixtures verbatim into a new worktree."""

    primary = _resolved(repository_root)
    worktree = _resolved(worktree_root)
    copied: list[dict[str, Any]] = []
    missing: list[str] = []
    for relative in required_paths:
        source = (primary / relative).resolve()
        target = (worktree / relative).resolve()
        if not _inside(source, primary) or not _inside(target, worktree):
            raise IsolationError(f"fixture path escapes repository/worktree: {relative}")
        if not source.exists():
            missing.append(str(relative).replace("\\", "/"))
            continue
        if source.is_dir():
            shutil.copytree(source, target, dirs_exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        copied.append({"source": str(source), "target": str(target), "kind": "directory" if source.is_dir() else "file"})
    report = {
        "repository_root": str(primary),
        "worktree_root": str(worktree),
        "required_paths": [str(item).replace("\\", "/") for item in required_paths],
        "copied": copied,
        "missing": missing,
        "valid": not missing and all((worktree / item).exists() for item in required_paths),
    }
    if not report["valid"]:
        raise IsolationError(f"required worktree fixtures are missing: {', '.join(missing) or 'copy verification failed'}")
    return report


def validate_required_fixture_sources(
    repository_root: str | Path,
    *,
    required_paths: tuple[Path, ...] = REQUIRED_FIXTURE_PATHS,
) -> dict[str, Any]:
    """Validate source fixtures before an implementation job is created."""

    primary = _resolved(repository_root)
    missing = [
        str(relative).replace("\\", "/")
        for relative in required_paths
        if not (primary / relative).exists()
    ]
    report = {
        "repository_root": str(primary),
        "required_paths": [str(item).replace("\\", "/") for item in required_paths],
        "missing": missing,
        "valid": not missing,
    }
    if missing:
        raise IsolationError(f"required source fixtures are missing: {', '.join(missing)}")
    return report


def sanitized_environment_report(environment_report: dict[str, Any]) -> dict[str, Any]:
    """Return a compact non-secret environment artifact."""

    return json.loads(redact_secrets(json.dumps(environment_report, sort_keys=True)))
