/** @jsxImportSource smithers-orchestrator */
import { createSmithers, Sequence, Task } from "smithers-orchestrator";
import { z } from "zod/v4";
import { agents } from "../agents";

const implementation = z.object({ status: z.string(), summary: z.string(), testsPassed: z.boolean(), strategyIdentity: z.string(), adapterIdentity: z.string() });
const phaseAData = z.object({ status: z.string(), summary: z.string(), archiveCount: z.number().int(), datasetHash: z.string().nullable(), barDatasetHash: z.string().nullable() });
const phaseASelection = z.object({ status: z.string(), summary: z.string(), selectedCandidateId: z.string().nullable(), frozenCandidateHash: z.string().nullable(), phaseAComplete: z.boolean() });
const finalResult = z.object({ status: z.string(), summary: z.string(), finalReportPath: z.string().nullable(), phaseBStatus: z.string().nullable(), alphaStatus: z.string().nullable(), studyExecuted: z.boolean() });
const { Workflow, outputs, smithers } = createSmithers({ implementation, phaseAData, phaseASelection, finalResult });
const spec = "C:/Users/sandr/Trading-Bot-Fib/.smithers/specs/imbalance-vwap-ride-btc-long-only-v4.md";
const root = "C:/Users/sandr/Trading-Bot-Fib";

export default smithers(() => <Workflow name="imbalance-vwap-ride-btc-long-only-v4"><Sequence>
  <Task id="implement-and-verify-v4" output={outputs.implementation} agent={agents.smart} retries={1} timeoutMs={150 * 60_000} heartbeatTimeoutMs={20 * 60_000}>{`Read ${spec} completely. Work only in ${root}. Implement V4 source, CLI, immutable artifact tools, and tests. Do not invoke Smithers, create another workflow, use external market data, execute a real study, or modify V1/V2/V3. V3 is read-only context only. Run focused V4 tests, full research_pipeline tests, compileall, and git diff --check; repair failures. Never transmit raw aggregate rows or use secrets/live orders. Return only schema-valid JSON.`}</Task>
  <Task id="acquire-and-validate-phase-a-v4" output={outputs.phaseAData} agent={agents.smart} retries={1} timeoutMs={6 * 60 * 60_000} heartbeatTimeoutMs={20 * 60_000}>{`Read ${spec} completely. Work in ${root}. Verify the V4 implementation and tests are sound; do not modify V1/V2/V3 or run candidates. Acquire/reuse/validate/normalize/atomically commit only official Binance USD-M BTCUSDT 2023-01 through 2023-12 archives and build separate bounded-memory Phase A 5m bar/footprint data. Use only the exact scope and integrity/resume rules in the spec. Never transmit raw rows. Return only schema-valid JSON.`}</Task>
  <Task id="execute-phase-a-select-and-freeze-v4" output={outputs.phaseASelection} agent={agents.smart} retries={1} timeoutMs={12 * 60 * 60_000} heartbeatTimeoutMs={20 * 60_000}>{`Read ${spec} completely. Work in ${root}, using only committed V4 Phase A data. Do not acquire Phase B data. Verify gates, then execute exactly the four sealed candidates on 2023 once each, write immutable candidate/root artifacts, apply literal deterministic eligibility/ranking, and freeze at most one. If none passes, persist PHASE_A_NO_ROBUST_CANDIDATE without Phase B/Alpha. Preserve V1/V2/V3 and never send raw rows. Return only schema-valid JSON.`}</Task>
  <Task id="phase-b-alpha-and-finalize-v4" output={outputs.finalResult} agent={agents.smart} retries={1} timeoutMs={6 * 60 * 60_000} heartbeatTimeoutMs={20 * 60_000}>{`Read ${spec} completely. Work in ${root}. Inspect immutable V4 Phase A selection. If no selection, validate and finalize without Phase B/Alpha. If selected, acquire/reuse/validate/normalize only 2025-02 through 2025-07 official BTCUSDT archives, build separate Phase B data, run exactly the frozen candidate once, enforce locked gates, and only on pass retrieve/version official current Alpha 25K Zero and MBT public rules before executing the Phase-B-only deterministic proxy. Complete final/preservation artifacts. Preserve V1/V2/V3, no secrets/live orders/raw disclosure, and return only schema-valid JSON.`}</Task>
</Sequence></Workflow>);
