from enum import StrEnum


class PipelineState(StrEnum):
    STRATEGY_DRAFT = "STRATEGY_DRAFT"
    WAITING_FOR_SPEC_APPROVAL = "WAITING_FOR_SPEC_APPROVAL"
    IMPLEMENTATION = "IMPLEMENTATION"
    IMPLEMENTATION_VERIFICATION = "IMPLEMENTATION_VERIFICATION"
    TECHNICAL_INTEGRITY_VERIFICATION = "TECHNICAL_INTEGRITY_VERIFICATION"
    TECHNICAL_REPAIR_REQUIRED = "TECHNICAL_REPAIR_REQUIRED"
    INSUFFICIENT_DIAGNOSTIC_DATA = "INSUFFICIENT_DIAGNOSTIC_DATA"
    BASELINE_BACKTEST = "BASELINE_BACKTEST"
    EDGE_GATE = "EDGE_GATE"
    PARAMETER_RESEARCH = "PARAMETER_RESEARCH"
    CANDIDATE_FREEZE = "CANDIDATE_FREEZE"
    WALK_FORWARD = "WALK_FORWARD"
    HOLDOUT = "HOLDOUT"
    STRESS_TESTS = "STRESS_TESTS"
    THROUGHPUT = "THROUGHPUT"
    RISK_SIZING = "RISK_SIZING"
    PROP_SIMULATION = "PROP_SIMULATION"
    MULTI_STRATEGY_PORTFOLIO = "MULTI_STRATEGY_PORTFOLIO"
    FINAL_REVIEW = "FINAL_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    TECHNICAL_FAILURE = "TECHNICAL_FAILURE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class DecisionType(StrEnum):
    CONTINUE = "CONTINUE"
    STOP = "STOP"
    REJECT = "REJECT"
    ACCEPT = "ACCEPT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    TECHNICAL_REPAIR_REQUIRED = "TECHNICAL_REPAIR_REQUIRED"


class GateOutcomeStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class ApprovalStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"


class ExperimentStatus(StrEnum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


TERMINAL_STATES = frozenset(
    {
        PipelineState.ACCEPTED,
        PipelineState.REJECTED,
        PipelineState.INSUFFICIENT_EVIDENCE,
        PipelineState.TECHNICAL_FAILURE,
        PipelineState.MANUAL_REVIEW_REQUIRED,
        PipelineState.INSUFFICIENT_DIAGNOSTIC_DATA,
    }
)
